// Generated by CoffeeScript 1.7.1
(function() {
  var CIE76;

  CIE76 = function(lab1, lab2) {
    var sum;
    sum = 0;
    lab1.forEach(function(val, i) {
      return sum += Math.pow(val - lab2[i], 2);
    });
    return Math.sqrt(sum);
  };

  module.exports = CIE76;

}).call(this);
